stages:
    - deploy
    - staging
  
  deploy-to-vercel:
    stage: deploy
    image: node:13.10.1-alpine3.10
  
    script:
      - npm i -g vercel
      - DEPLOYMENT_URL=$(vercel -t $VERCEL_TOKEN_DEV --confirm)
      - echo $DEPLOYMENT_URL >vercel_deployment_url.txt
  
    artifacts:
      when: on_success
      paths:
        - vercel_deployment_url.txt
  
  staging:
    image: cypress/browsers:node12.16.2-chrome81-ff75
    stage: staging
  
    script:
      - DEPLOYMENT_URL=$(cat vercel_deployment_url.txt)
      - npm ci
      - $(npm bin)/cypress run --env CYPRESS_BASE_URL=$DEPLOYMENT_URL
    only:
      - dev
  
    artifacts:
      when: on_success
      paths:
        - cypress/screenshots
        - cypress/videos